services:

  frontend:

    build:
      context: ../i-computers-frontend
      args:
        VITE_BACKEND_URL: http://13.53.231.133/api

    ports:
      - "8080:80"

    depends_on:
      - backend



  backend:

    image: gaurawawickramasinghe/icomputers-backend:latest

    ports:
      - "3000:3000"

    env_file:
      - ./i-computers-backend/.env